@csFhirApiSample_HostAddress = https://localhost:7124

GET {{csFhirApiSample_HostAddress}}/weatherforecast/
Accept: application/json

###

@patientId=1398961
GET {{csFhirApiSample_HostAddress}}/patient?patientId={{patientId}}

###
